name: Android CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Install Android SDK components
      run: |
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

    - name: Install Gradle 8.7
      run: |
        wget https://services.gradle.org/distributions/gradle-8.7-bin.zip
        unzip -q -d "$HOME/gradle" gradle-8.7-bin.zip
        echo "$HOME/gradle/gradle-8.7/bin" >> "$GITHUB_PATH"
        gradle --version

    - name: Build with Gradle
      run: gradle assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: myapp-debug-apk
        path: app/build/outputs/apk/debug/*.apk
